### ISSUE TITLE
Bug: Commands containing ! fail to send to device

### ISSUE THREAD

**Issue by kevmullet100** [v1tal3/netconfig#13]
I was setting up read only access to our 5K's for our server team with the command:

username serverteam password RandomPasswordContainingAn! role network-operator

The ! in the password stopped the command from sending to the device, remove the ! and the command sends successfully

**Comment by matt852** [comment]
Did you send this in the iShell?  Or how did you enter the configuration change?

**Comment by kevmullet100** [comment]
Hmmm.. I think I tried both within iShell and the small command window
I've rebooted my Ubuntu box and now netconfig is not coming back online... once I have fixed that I will confirm

**Comment by kevmullet100** [comment]
OK I have just tried again and it is accepting it. 
I think this may be a user error...

**Comment by kevmullet100** [comment]
Figured out my user error on this one. The commands are not accepted with the Enter key on the num pad, but are with Enter. Again probably a local issue.

**Comment by matt852** [comment]
I've filed this as a bug, and pushed a fix in the development branch.  Thanks for bringing this up.

**Comment by matt852** [comment]
Closing bug
