### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by ghost** [v1tal3/netconfig#28]
Got this error

error: <class 'xmlrpclib.Fault'>, <Fault 92: "CANT_REREAD: File contains no section headers.\nfile: /etc/supervisor/conf.d/netconfig.conf, line: 1\n'  [program:netconfig]\\n'">: file: /usr/lib/python2.7/xmlrpclib.py line: 800

You need to remove the spaces before the lines of text here at the "Contents of /etc/supervisor/conf.d/netconfig.conf" section

[program:netconfig]
command = gunicorn app:app -b localhost:8000
directory = /home/netconfig/netconfig
user = netconfig

**Comment by matt852** [comment]
There are no spaces before the lines of text in the referenced section.  I don't see any issue here.

**Comment by wmann** [comment]
I had the same issue like ckakoczki. The problem are the spaces in the code snippets on http://netconfig.readthedocs.io/en/latest/installation/ubuntu16-04.html
There are 2 space in front of each line.

**Comment by dbethke** [comment]
could it be because those code blocks are rendered slightly different when they use line numbers.
I noticed some of the code blocks use
> .. code-block:: text

while others use: 

> .. code-block:: text
   :linenos:

Maybe if the linenos are removed, we won't get the extra spaces inserted in the rendered text.

see [raw docs](https://raw.githubusercontent.com/v1tal3/netconfig/master/docs/installation/ubuntu16-04.rst)

**Comment by dbethke** [comment]
also noticed that the md rendering on [github](https://github.com/v1tal3/netconfig/blob/master/docs/installation/ubuntu16-04.rst) doesn't show the blocks that have `:linenos:` while it does get rendered on the [readthedocs site](https://netconfig.readthedocs.io/en/latest/installation/ubuntu16-04.html)

**Comment by matt852** [comment]
This is fixed in the latest development branch, and will be included in the next primary update.  Thanks for the issue and fix.
