### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by PaddyMack** [v1tal3/netconfig#30]
I was following the guid : http://netconfig.readthedocs.io/en/latest/installation/ubuntu16-04.html

Following everything exactly as posted, I get an error at the point of restarting netconfig:

> netconfig@UBNT-SVR-03:~/netconfig$ sudo supervisorctl restart netconfig
> netconfig: stopped
> netconfig: ERROR (spawn error)

Supervisor will now not start netconfig. 

Investigating the logs shows 

> netconfig@UBNT-SVR-03:/var/log/supervisor$ cat supervisord.log
> 2017-12-29 11:20:29,648 CRIT Supervisor running as root (no user in config file)
> 2017-12-29 11:20:29,650 WARN No file matches via include "/etc/supervisor/conf.d/*.conf"
> 2017-12-29 11:20:29,661 INFO RPC interface 'supervisor' initialized
> 2017-12-29 11:20:29,661 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2017-12-29 11:20:29,661 INFO supervisord started with pid 9488
> 2017-12-29 11:40:07,800 INFO spawned: 'netconfig' with pid 9914
> 2017-12-29 11:40:08,000 INFO exited: netconfig (exit status 3; not expected)
> 2017-12-29 11:40:09,002 INFO spawned: 'netconfig' with pid 9921
> 2017-12-29 11:40:09,201 INFO exited: netconfig (exit status 3; not expected)
> 2017-12-29 11:40:10,355 INFO spawned: 'netconfig' with pid 9928
> 2017-12-29 11:40:10,542 INFO exited: netconfig (exit status 3; not expected)
> 2017-12-29 11:40:13,554 INFO spawned: 'netconfig' with pid 9934
> 2017-12-29 11:40:13,739 INFO exited: netconfig (exit status 3; not expected)
> 2017-12-29 11:40:14,741 INFO gave up: netconfig entered FATAL state, too many start retries too quickly

After a reboot 

> 2017-12-29 12:29:13,515 CRIT Supervisor running as root (no user in config file)
> 2017-12-29 12:29:13,516 INFO Included extra file "/etc/supervisor/conf.d/netconfig.conf" during parsing
> 2017-12-29 12:29:13,562 INFO RPC interface 'supervisor' initialized
> 2017-12-29 12:29:13,562 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2017-12-29 12:29:13,562 INFO supervisord started with pid 1175
> 2017-12-29 12:29:14,564 INFO spawned: 'netconfig' with pid 1473
> 2017-12-29 12:29:15,121 INFO exited: netconfig (exit status 3; not expected)

The file "/etc/supervisor/conf.d/netconfig.conf" is as expected, identical to that in the installation instructions. 

Going through the .conf file, all the resources it references are correct (as far as I can see), /home/netconfig/netconfig exists and is populated, user netconfig exists and has root.

Not sure how to proceed from here.

**Comment by matt852** [comment]
What are the permissions on the netconfig.conf file?
What are the permissions for the Netconfig folder?
What are the contents of the netconfig.conf file?
Make sure there are no leading spaces in any of the 4 lines, as other users reported issues if there were spaces in front of the lines.  Note that the Install guide shows spaces in front, but this is an HTML formatting mistake and will be fixed in the next update.

**Comment by matt852** [comment]
No reply in 9 days.  Closing issue.
