### ISSUE TITLE
Some links go to HTTP instead of HTTPS

### ISSUE THREAD

**Issue by sn3ak** [v1tal3/netconfig#43]
In my Environment, I must turn off HTTP which breaks a few links.

Initial Login redirect,  Using Home  and  Network -> View Devices links go to http://my.int.ip.addr/db/viewhosts/ most of the other links appear to work correctly.

Close Active SSH Sessions also appears go to http://my.int.ip.addr/index

I'm currently running 1.2.3 beta, but this problem has existed since the first release.

It may also be desirable to run on a non-standard HTTPS port, which most of the pages does work with.

Thanks for the great software and hard work.

**Comment by matt852** [comment]
Thanks for the bug report.  I'm able to see the HTTP traffic you're referring to via Wireshark, but then it immediately redirects back to HTTPS.  I'm not sure why this is occurring, but I'll be looking into it ASAP.

**Comment by matt852** [comment]
I think I found a fix last night, but it involves editing one of the nginx files created during installation.  Can you try this and tell me if it's working?  If so I'll deploy it and figure out a way to patch it in.

**5 Steps Total:**
1.  SSH into your NetConfig server
2.  Run this command to edit the Nginx NetConfig file:

`sudo vi /etc/nginx/sites-available/netconfig`

3.  In the file, add the following 2 lines in the section "location / {", under the existing proxy_set_header lines:
```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

4.  Save and quit the file
5.  Restart the nginx service

`sudo service nginx restart`

After doing the above steps, I know longer see any HTTP traffic for any redirects like you mentioned previously.


For reference, the complete /etc/nginx/sites-available/netconfig should look like this:

```
server {
       listen         80;
       server_name    netconfig.domain.com;
       return         301 https://$host$request_uri;
}

server {
    listen 443;
    server_name netconfig.domain.com;

    ssl on;
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    location / {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /netconfig {
        alias  /home/netconfig/netconfig/app/;
    }
}
```
