### ISSUE TITLE
Error 500 on View Device page following upgrade to 1.3.1

### ISSUE THREAD

**Issue by kevmullet100** [v1tal3/netconfig#49]
I have upgraded to 1.3.1.
When logging in or clicking on View Devices, it shows Error 500 page.
Can't view  any devices?
I'm sure its a local thing?

**Comment by matt852** [comment]
Did you run the upgrade.sh script yet?  Did it throw any errors when running?

**Comment by kevmullet100** [comment]
No errors when running upgrade.sh 
Tried it again to no avail.

**Comment by matt852** [comment]
Were you upgrading from 1.2.3, or another version?
Are you using the local database, or pulling from NetBox?

I need to add error output to the '500 error' page in the next release.  But for now, can you please SSH into NetConfig as user 'netconfig' and modify this file:

`!/netconfig/app/templates/errors/500.html`

At the bottom, just above the line '{% endblock %}', add this line:

`Error: {{ error }}`

Save and quit.  Run 'sudo supervisorctl restart netconfig' to restart the service.  Then try a full refresh on the web page.  When the 500 Error page shows again, it should display more detail about the error.  Let me know what that says.

Once all this is done, you'll want to discard your changes, or you may end up with merge conflicts when updating to a future release.  To do so, SSH back in, then run these commands:

`cd ~/netconfig`
`git checkout -- .`
`git status`

The 'git status' output should return 'nothing to commit, working directory clean'  Let me know if you run into any issues.

**Comment by kevmullet100** [comment]
I thought I was keeping pace with updates, but may have missed one? Not sure on the previous version though!


Output is
Error: (sqlite3.OperationalError) no such column: host.local_creds [SQL: u'SELECT host.id AS host_id, host.hostname AS host_hostname, host.ipv4_addr AS host_ipv4_addr, host.type AS host_type, host.ios_type AS host_ios_type, host.local_creds AS host_local_creds, host.devicetype_id AS host_devicetype_id \nFROM host ORDER BY host.hostname ASC\n LIMIT ? OFFSET ?'] [parameters: (10000, 0)]

So looks like I must have missed an upgrade?!

**Comment by matt852** [comment]
No I think you're ok.  The upgrade.sh script should handle this.  This error is because the local database wasn't updated properly with the new schema, to account for local credential handling.

In the ~/netconfig folder, try this command manually:

`python db_upgrade.py`

Let me know its output, and if that fixes anything.  It should say "Current database version: 17".

**Comment by kevmullet100** [comment]
I get this when running the db_upgrade.py:
migrate.exceptions.VersionNotFoundError: "Database schema file with version 1 doesn't exist."

**Comment by matt852** [comment]
I found a fix for this.  I'll get a new update pushed for this by EOD today.  Thanks for bringing this to my attention.

**Comment by matt852** [comment]
This issue should be resolved in 1.3.2.  Please upgrade your version, run the upgrade.sh script again, and let me know if you run into any issues.  I'll keep this issue open for a few days to hear back your results.

**Comment by kevmullet100** [comment]
Perfect, that has worked a treat!

Thank You!

**Comment by matt852** [comment]
Thanks for verifying.  Sorry about that mix up.  It boiled down to a version mismatch on my local SQLAlchemy database I use in testing v16, and the fact everyone using NetConfig is starting from scratch with v0.

When I implemented a database scheme change in v1.3.x, it updated my version to v17, but everyone else was expecting to update to v1, so the db_upgrade.py and db_migrate.py script couldn't find a "001_migration.py" schema upgrade file, only a "017_migration.py" file.
