### ISSUE TITLE
Request: Add descriptions to interfaces in View Host Interfaces page

### ISSUE THREAD

**Issue by kevmullet100** [v1tal3/netconfig#6]
Would it be possible to add the port description to the View Host Interfaces page?

**Comment by matt852** [comment]
Port descriptions can get very long, and could impact the condensed, to the point layout I'm looking for on the device page.  Where specifically did you have in mind?  How would you better display it?

**Comment by kevmullet100** [comment]
Selfish reasons really, our estate relies heavily on accurate port descriptions, and the first command when logging on to any device is usually _show int description_, which encompasses everything you have on that screen which looks to be the output of _show ip int brief_ except the IP addressing.

I only wish I had any programming ability to help you on this!

**Comment by matt852** [comment]
Correct, it is pretty much "show ip int brief", except I do have the IP addresses on there as well.

I have an idea on this, but I've never done it before so I'll need some time to figure it out.  I can utilize the framework for a dropdown style output for "show int description" along with other one-off commands I'm sure people will want.

**Comment by zendainc** [comment]
Why not make it a toggle setting. So a user can choose to display port descriptions?

**Comment by kevmullet100** [comment]
So after poking about a bit more, on the NX-OS devices, it has the interface names on this page, which I assume is pulled from the description of the port?

**Comment by matt852** [comment]
i forgot about that.  I'll see if I can add in descriptions just like with NX-OS devices.  I can make it toggleable later on.

**Comment by matt852** [comment]
The backend structure for displaying device interface information has been reworked, and descriptions are now reenabled for NX-OS devices.  I will be working on getting descriptions added for IOS devices in the next couple of days.

**Comment by matt852** [comment]
All descriptions have now been added (if they exist), and truncated to 25 characters or less, in the latest development branch update.

**Comment by matt852** [comment]
Added in v1.3.5.  Closing issue
