### ISSUE TITLE
Request: Privileged EXEC Mode

### ISSUE THREAD

**Issue by kikaida** [v1tal3/netconfig#7]
Is there a way to insert my enable secret? I can only run commands at User Exec mode.
`Switch>show run
                      ^
% Invalid input detected at '^' marker.
Switch>`

**Comment by kevmullet100** [comment]
When you SSH to your switches do you then have to type enable to enter privilege exec mode?
I think the netconfig implementation currently supports a login methodology of the tacacs+ / AD style where you do not need to enable when you log in.

Maybe a future revision could have different credentials for differing devices. I have some switches that do not support our version of tacacs+ so I have to log into netconfig with the local credentials of those switches to be able to manage them through netconfig. Obviously I cannot then manage the ones that AAA to tacacs+

**Comment by matt852** [comment]
This feature is now supported as of feature 1.3.1.  Closing issue.
