### ISSUE TITLE
Error Page 404

### ISSUE THREAD

**Issue by EarlRamirez** [v1tal3/netconfig#81]
Dear @v1tal3 

Thank you for the remarkable tool that you and the project contributors made.

Recently, when I try to edit the configuration for a switch, e.g. changing the VLAN I get the following error.
![image](https://user-images.githubusercontent.com/12306859/41988243-8306de84-7a09-11e8-9586-54b8313f34cc.png)

The URL that I getting the error from is http://192.168.122.141/results/resultsinterfaceedit/16/251/0/?int=GigabitEthernet0/3

To re-create this issue
- Select the switch that you will like to modify
- Click on the icon to edit the desired port
- Update the access, voice or other information
- Hit submit
Instead of _Interface was successfully edited_ you will get error page 404.

**Comment by matt852** [comment]
Thanks for the issue Earl.

1. What version of NetConfig are you running?
2. After you submit your interface config change, and it gives you the 404 error, go back to the interface (either in NetConfig or manually via CLI) and see if the new changes actually applied.  Did they?  Or did it error out before applying the changes?
3.  Does this happen on all ports, or just this one specific port?

**Comment by EarlRamirez** [comment]
- I am running NetConfig version 1.3.5 (beta)
- Unfortunately, the error is happening before the changes are applied
- Yes, it happens for all port on any of the network switches that are in NetConfig

Checked a few things and noticed that I need to full all three columns _access_, _voice_ and _other_ and it will work; however, most of the times we only need to update one of the three not all three.

**Comment by matt852** [comment]
Hi Earl, I was able to successfully test this today.  I'm looking into what the issue is tonight.

I did find if you enter something only in the textbox for Other, it works.

**Comment by matt852** [comment]
Fix has been applied in v1.3.6.

**Comment by EarlRamirez** [comment]
@v1tal3 thanks a lot, it worked like a charm
